# Generated by Django 4.2.6 on 2023-10-11 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_expenses', '0002_alter_usuario_id_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_expenses.evento'),
        ),
    ]
