# Generated by Django 4.2.6 on 2023-10-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_expenses', '0003_alter_usuario_id_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(editable=False, max_length=254, primary_key=True, serialize=False),
        ),
    ]
