# Generated by Django 4.2.6 on 2023-10-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_expenses', '0004_alter_usuario_correo_electronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
